### ISSUE TITLE
Data formatting issues

### ISSUE THREAD

**Issue by GaiYu0** [odashi/ase15-django-dataset#2]
First, I would like to thank the creators of the dataset for providing a valuable resource for my research.

I noticed two formatting issues in the data:
* The code in `all.code` does not seem properly indented.
* About 1500 lines in `all.anno` are likely "wrapped" into the next. For example, at the beginning of `all.anno`:
```
  __all__ is an list containing 6 elements: 'get_cache', 'cache', 'DEFAULT_CACHE_ALIAS', 'InvalidCacheBackendError',
  'CacheKeyWarning' and 'BaseCache'   DEFAULT_CACHE_ALIAS is a string 'default'.
```

The issues make it hard to fully exploit the data, so I'm wondering if there is a solution. I'm happy to work on one if there is none.

**Comment by odashi** [comment]
@GaiYu0 Thanks for reporting!

> The code in all.code does not seem properly indented.

We originally intended to use this dataset for line-to-line translation between code/text. During the process of making the dataset, we didn't care about maintaining correct indentations.

> About 1500 lines in all.anno are likely "wrapped"

Yeah this is known annotation errors (maybe due to insufficient annotation guidelines). We didn't count how many examples in the dataset involves this error.
Since you suggested "about 1500 lines", I guessed you might have some knowledge about it. Is it possible to provide a list of line numbers that the problem happens?

**Comment by GaiYu0** [comment]
Thank you @odashi! Most lines containing three white spaces seem problematic (try `cat ase15-django-dataset/django/all.anno | grep "\ \ \ "`). Proper indentations are valuable because many lines are trivial by themselves, such as else (595 lines) and try (431 lines).

**Comment by odashi** [comment]
@GaiYu0 This dataset didn't take any care of the order of lines while creating. Although some lines look to have a consistent order (and I think most lines are actually so), we couldn't guarantee what happens if we take care of remaining indentations.

**Comment by odashi** [comment]
I'd close this issue for now. Feel free to re-open if it is necessary to have more discussions.
